import { describe, it, expect } from 'vitest';
import {
    formatSummaryMarkdown,
    formatChangelogEntry,
    formatPRDescription,
} from '../src/formatter';
import { CommitCategory, GroupedCommits } from '../src/types';

// ── Test fixtures ────────────────────────────────────────────────────

function emptyGroups(): GroupedCommits {
    return {
        [CommitCategory.Features]: [],
        [CommitCategory.Fixes]: [],
        [CommitCategory.Docs]: [],
        [CommitCategory.Refactors]: [],
        [CommitCategory.Tests]: [],
        [CommitCategory.Chores]: [],
        [CommitCategory.Other]: [],
    };
}

function sampleGroups(): GroupedCommits {
    return {
        ...emptyGroups(),
        [CommitCategory.Features]: [
            { hash: 'abc1234567890', message: 'add login', category: CommitCategory.Features, scope: 'auth' },
            { hash: 'def4567890123', message: 'add dark mode', category: CommitCategory.Features },
        ],
        [CommitCategory.Fixes]: [
            { hash: 'ghi7890123456', message: 'fix null pointer', category: CommitCategory.Fixes },
        ],
    };
}

// ── formatSummaryMarkdown ────────────────────────────────────────────

describe('formatSummaryMarkdown', () => {
    it('includes tag range when tag is provided', () => {
        const md = formatSummaryMarkdown(sampleGroups(), 'v0.1.0', 3);
        expect(md).toContain('Changes since `v0.1.0`');
        expect(md).toContain('**3 commits**');
    });

    it('shows "no tags found" when tag is null', () => {
        const md = formatSummaryMarkdown(sampleGroups(), null, 3);
        expect(md).toContain('Recent changes (no tags found)');
    });

    it('uses singular "commit" for count of 1', () => {
        const md = formatSummaryMarkdown(emptyGroups(), null, 1);
        expect(md).toContain('**1 commit**');
    });

    it('renders category sections with commit lines', () => {
        const md = formatSummaryMarkdown(sampleGroups(), null, 3);
        expect(md).toContain('### Features');
        expect(md).toContain('- **auth:** add login (`abc1234`)');
        expect(md).toContain('- add dark mode (`def4567`)');
        expect(md).toContain('### Fixes');
        expect(md).toContain('- fix null pointer (`ghi7890`)');
    });

    it('omits empty categories', () => {
        const md = formatSummaryMarkdown(sampleGroups(), null, 3);
        expect(md).not.toContain('### Docs');
        expect(md).not.toContain('### Refactors');
        expect(md).not.toContain('### Tests');
        expect(md).not.toContain('### Chores');
        expect(md).not.toContain('### Other');
    });

    it('renders no category sections when all empty', () => {
        const md = formatSummaryMarkdown(emptyGroups(), null, 0);
        expect(md).not.toContain('###');
    });
});

// ── formatChangelogEntry ─────────────────────────────────────────────

describe('formatChangelogEntry', () => {
    it('starts with version and date header', () => {
        const md = formatChangelogEntry(sampleGroups(), '1.0.0', '2026-02-25');
        expect(md).toMatch(/^## \[1\.0\.0\] - 2026-02-25/);
    });

    it('includes grouped commit lines', () => {
        const md = formatChangelogEntry(sampleGroups(), '1.0.0', '2026-02-25');
        expect(md).toContain('### Features');
        expect(md).toContain('- **auth:** add login (`abc1234`)');
    });
});

// ── formatPRDescription ──────────────────────────────────────────────

describe('formatPRDescription', () => {
    it('starts with release title', () => {
        const md = formatPRDescription(sampleGroups(), '1.0.0');
        expect(md).toMatch(/^# Release 1\.0\.0/);
    });

    it('includes total commit count', () => {
        const md = formatPRDescription(sampleGroups(), '1.0.0');
        expect(md).toContain('**3 commits**');
    });

    it('includes forge-cli footer', () => {
        const md = formatPRDescription(sampleGroups(), '1.0.0');
        expect(md).toContain('*Generated by forge-cli*');
    });

    it('includes grouped sections', () => {
        const md = formatPRDescription(sampleGroups(), '1.0.0');
        expect(md).toContain('### Features');
        expect(md).toContain('### Fixes');
    });
});
