import { GroupedCommits, ParsedCommit } from './types';
import { CATEGORY_ORDER, COMMIT_HASH_SHORT_LENGTH } from './constants';

// ── Helpers ──────────────────────────────────────────────────────────

function pluralize(count: number, word: string): string {
  return `${count} ${word}${count !== 1 ? 's' : ''}`;
}

function formatCommitLine(commit: ParsedCommit): string {
  const scope = commit.scope ? `**${commit.scope}:** ` : '';
  const shortHash = commit.hash.slice(0, COMMIT_HASH_SHORT_LENGTH);
  return `- ${scope}${commit.message} (\`${shortHash}\`)`;
}

function renderGroupedSection(grouped: GroupedCommits): string {
  const sections: string[] = [];

  for (const category of CATEGORY_ORDER) {
    const commits = grouped[category];
    if (commits.length === 0) continue;

    sections.push(`### ${category}\n`);
    for (const commit of commits) {
      sections.push(formatCommitLine(commit));
    }
    sections.push('');
  }

  return sections.join('\n').trimEnd();
}

function countTotal(grouped: GroupedCommits): number {
  return CATEGORY_ORDER.reduce((sum, cat) => sum + grouped[cat].length, 0);
}

// ── Public formatters ────────────────────────────────────────────────

/**
 * Format a clean Markdown summary of grouped commits.
 */
export function formatSummaryMarkdown(
  grouped: GroupedCommits,
  tag: string | null,
  totalCommits: number,
): string {
  const range = tag ? `Changes since \`${tag}\`` : 'Recent changes (no tags found)';

  return [
    `## 📋 Commit Summary`,
    '',
    `> ${range} — **${pluralize(totalCommits, 'commit')}**`,
    '',
    renderGroupedSection(grouped),
    '',
  ].join('\n');
}

/**
 * Format a changelog entry with version header and ISO date.
 */
export function formatChangelogEntry(
  grouped: GroupedCommits,
  version: string,
  date: string,
): string {
  return [`## [${version}] - ${date}`, '', renderGroupedSection(grouped), ''].join('\n');
}

/**
 * Format a PR description draft from grouped commits.
 */
export function formatPRDescription(grouped: GroupedCommits, version: string): string {
  const total = countTotal(grouped);

  return [
    `# Release ${version}`,
    '',
    `This PR includes **${pluralize(total, 'commit')}**.`,
    '',
    renderGroupedSection(grouped),
    '',
    '---',
    '',
    `*Generated by forge-cli*`,
    '',
  ].join('\n');
}
