import { CommitCategory, GroupedCommits, ParsedCommit } from './types';

// Categories in display order
const CATEGORY_ORDER: CommitCategory[] = [
    CommitCategory.Features,
    CommitCategory.Fixes,
    CommitCategory.Docs,
    CommitCategory.Refactors,
    CommitCategory.Tests,
    CommitCategory.Chores,
    CommitCategory.Other,
];

// ── Helpers ──────────────────────────────────────────────────────────

function formatCommitLine(commit: ParsedCommit): string {
    const scope = commit.scope ? `**${commit.scope}:** ` : '';
    return `- ${scope}${commit.message} (\`${commit.hash.slice(0, 7)}\`)`;
}

function renderGroupedSection(grouped: GroupedCommits): string {
    const sections: string[] = [];

    for (const category of CATEGORY_ORDER) {
        const commits = grouped[category];
        if (commits.length === 0) continue;

        sections.push(`### ${category}\n`);
        for (const commit of commits) {
            sections.push(formatCommitLine(commit));
        }
        sections.push(''); // blank line between sections
    }

    return sections.join('\n').trimEnd();
}

// ── Public formatters ────────────────────────────────────────────────

/**
 * Format a clean Markdown summary of grouped commits.
 */
export function formatSummaryMarkdown(
    grouped: GroupedCommits,
    tag: string | null,
    totalCommits: number,
): string {
    const range = tag ? `Changes since \`${tag}\`` : 'Recent changes (no tags found)';
    const lines: string[] = [
        `## 📋 Commit Summary`,
        '',
        `> ${range} — **${totalCommits}** commit${totalCommits !== 1 ? 's' : ''}`,
        '',
        renderGroupedSection(grouped),
        '',
    ];

    return lines.join('\n');
}

/**
 * Format a changelog entry with version header and ISO date.
 */
export function formatChangelogEntry(
    grouped: GroupedCommits,
    version: string,
    date: string,
): string {
    const lines: string[] = [
        `## [${version}] - ${date}`,
        '',
        renderGroupedSection(grouped),
        '',
    ];

    return lines.join('\n');
}

/**
 * Format a PR description draft from grouped commits.
 */
export function formatPRDescription(
    grouped: GroupedCommits,
    version: string,
): string {
    const totalCommits = CATEGORY_ORDER.reduce(
        (sum, cat) => sum + grouped[cat].length,
        0,
    );

    const lines: string[] = [
        `# Release ${version}`,
        '',
        `This PR includes **${totalCommits}** commit${totalCommits !== 1 ? 's' : ''}.`,
        '',
        renderGroupedSection(grouped),
        '',
        '---',
        '',
        `*Generated by forge-cli*`,
        '',
    ];

    return lines.join('\n');
}
